project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.md"

website:
  title: "Template"
  navbar:
     left:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: posts/about.qmd

execute: 
  freeze: auto

format:
  html:
    theme:
      - cosmo
    css: styles/styles.css
    csl: references/nuclear-medicine-and-molecular-imaging.csl
    code-copy: true
    toc: true
    mathjax: "default"
    link-external-newwindow: true
    number-sections: true
    include-after-body: utterances.html

